Repository ESCOMP/mizuRoute, pull requests merged in 2022-01, with the labels that each got.

#246 one bugfix and one small change to remove warning when compling with ifort
  route/build/src/mpi_process.f90
  route/build/src/pio_utils.f90
  route/build/src/write_restart_pio.f90
  route/build/src/write_simoutput_pio.f90
Labels: bugfix

#251 Add number of MPI tasks to restart file to ensure they are the same when reading
  cime_config/testdefs/testmods_dirs/mizuroute/default/user_nl_clm
  route/build/src/read_restart.f90
  route/build/src/write_restart_pio.f90
Labels: enhancement, cesm-coupling

#257 history file output option improvement
  route/build/src/write_simoutput.f90
Labels: enhancement
