Repository ESCOMP/mizuRoute, pull requests merged in 2023-08, with the labels that each got.

#412 capacity to scale or offset the inputs (runoff, evaporation, and precipitation)
  route/build/src/lake_route.f90
  route/build/src/public_var.f90
  route/build/src/read_control.f90
  route/build/src/read_streamSeg.f90
  route/build/src/standalone/get_basin_runoff.f90
Labels: new features, standalone

#415 Fix a restart issue for a single core
  route/build/src/mpi_process.f90
Labels: cesm-coupling, bugfix, standalone

#416 Remove testmod fixes for ccs_config
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_mizuRoute.xml
  cime_config/testdefs/testmods_dirs/mizuroute/5x5_amazon_rHDMA/include_user_mods
  cime_config/testdefs/testmods_dirs/mizuroute/5x5_amazon_rHDMA/shell_commands
  cime_config/testdefs/testmods_dirs/mizuroute/5x5_amazon_rHDMA_Monthly/include_user_mods
  cime_config/testdefs/testmods_dirs/mizuroute/MERIT/include_user_mods
  cime_config/testdefs/testmods_dirs/mizuroute/MERIT/shell_commands
  cime_config/testdefs/testmods_dirs/mizuroute/hcru/shell_commands
Labels: cesm-coupling, bugfix

#422 set runoff depth unit correctly in meta
  route/build/src/read_control.f90
Labels: cesm-coupling, bugfix, standalone

#423 Fix error in writing history_file variable for gauge-only history file in restart file
  route/build/src/pio_utils.f90
  route/build/src/write_restart_pio.f90
Labels: cesm-coupling, bugfix, standalone

#421 connect lake module to the other routing methods
  route/build/src/historyFile.f90
  route/build/src/lake_route.f90
  route/build/src/main_route.f90
Labels: cesm-coupling, standalone, infrastructure
