Repository ESCOMP/mizuRoute, pull requests merged in 2023-05, with the labels that each got.

#365 Readthedoc updates
  docs/source/Control_file.rst
  docs/source/Input_data.rst
Labels: cesm-coupling, standalone

#367 change testCase data link
  docs/source/testCase.rst
Labels: standalone

#368 develop: change testCase data link
  docs/source/testCase.rst
Labels: standalone

#364 reading aggregated history variables from restart netcdf
  route/build/Makefile
  route/build/src/globalData.f90
  route/build/src/histVars_data.f90
  route/build/src/historyFile.f90
  route/build/src/init_model_data.f90
  route/build/src/ncio_utils.f90
  route/build/src/pio_utils.f90
  route/build/src/standalone/model_setup.f90
  route/build/src/write_restart_pio.f90
  route/build/src/write_simoutput_pio.f90
Labels: cesm-coupling, new features, cleanup, standalone

#370 move git variable (version, gitBranch, gitHash) to standalone f90
  route/build/src/init_model_data.f90
  route/build/src/public_var.f90
  route/build/src/standalone/model_setup.f90
Labels: cesm-coupling, bugfix

#374 cesm-coupling bugfix
  route/settings/SAMPLE-coupled.control
Labels: cesm-coupling, bugfix

#373 use select type to compact the generic routine
  docs/source/conf.py
  route/build/src/ncio_utils.f90
  route/build/src/pio_utils.f90
Labels: cesm-coupling, cleanup, standalone

#379 Fix single core run error in cesm-coupling mode.
  route/build/cpl/RtmMod.F90
  route/build/src/init_model_data.f90
  route/build/src/mpi_process.f90
Labels: cesm-coupling, bugfix, standalone

#381 Fix cesm restarting:
  route/build/cpl/RtmMod.F90
  route/build/cpl/nuopc/rof_comp_nuopc.F90
  route/build/src/globalData.f90
  route/build/src/histVars_data.f90
  route/build/src/init_model_data.f90
  route/build/src/lake_route.f90
  route/build/src/mpi_process.f90
  route/build/src/read_control.f90
Labels: cesm-coupling, bugfix

#371 Add some lake tests to the test list update lake dataset and fix some coupled issues
  cime_config/buildnml
  cime_config/config_archive.xml
  cime_config/test/env_run.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_mizuRoute.xml
  cime_config/testdefs/testmods_dirs/mizuroute/5x5_amazon_rHDMA/include_user_mods
  cime_config/testdefs/testmods_dirs/mizuroute/5x5_amazon_rHDMA/shell_commands
  cime_config/testdefs/testmods_dirs/mizuroute/5x5_amazon_rHDMA_Monthly/include_user_mods
  cime_config/testdefs/testmods_dirs/mizuroute/MERIT/include_user_mods
  cime_config/testdefs/testmods_dirs/mizuroute/MERIT/shell_commands
  cime_config/testdefs/testmods_dirs/mizuroute/default/shell_commands
  cime_config/testdefs/testmods_dirs/mizuroute/default/user_ctl_mizuroute
  cime_config/testdefs/testmods_dirs/mizuroute/default/user_nl_mizuroute_control
  cime_config/testdefs/testmods_dirs/mizuroute/hcru/shell_commands
  cime_config/testdefs/testmods_dirs/mizuroute/monthly/user_ctl_mizuroute
  cime_config/testdefs/testmods_dirs/mizuroute/monthly/user_nl_mizuroute_control
  cime_config/user_nl_mizuroute_control
  route/build/cpl/RtmFileUtils.F90
  route/build/cpl/RtmMod.F90
  route/build/cpl/RtmVar.F90
  route/build/cpl/RunoffMod.F90
  route/build/cpl/nuopc/rof_comp_nuopc.F90
  route/build/cpl/nuopc/rof_import_export.F90
  route/build/cpl/nuopc/rof_shr_methods.F90
  route/build/src/process_remap.f90
  route/settings/SAMPLE-coupled.control
  route/settings/SAMPLE.control
Labels: enhancement, cesm-coupling

#393 history file name convention for gauge only output
  route/build/src/write_simoutput_pio.f90
Labels: enhancement, cesm-coupling, bugfix, standalone

#394 Including t_bound variable in a history file and resulting changes
  route/build/cpl/RtmTimeManager.F90
  route/build/src/globalData.f90
  route/build/src/histVars_data.f90
  route/build/src/historyFile.f90
  route/build/src/init_model_data.f90
  route/build/src/main_route.f90
  route/build/src/popMetadat.f90
  route/build/src/standalone/model_setup.f90
  route/build/src/var_lookup.f90
  route/build/src/write_restart_pio.f90
  route/build/src/write_simoutput_pio.f90
Labels: enhancement, cesm-coupling, cleanup, standalone
