Repository ESCOMP/mizuRoute, pull requests merged in 2023-04, with the labels that each got.

#345 Add a custom grid option for cesm-coupling
  cime_config/buildnml
Labels: enhancement

#360 bugfixes in init and run routines for ctsm-coupling
  route/build/Makefile
  route/build/cpl/RtmMod.F90
  route/build/src/globalData.f90
  route/build/src/init_model_data.f90
  route/build/src/public_var.f90
  route/build/src/read_control.f90
Labels: cesm-coupling, bugfix

#362 water can be abstracted from residual reach volume and outflow
  route/build/src/irf_route.f90
Labels: cesm-coupling, standalone, science

#363 Write git information in history file global attributes
  route/build/cpl/RtmVar.F90
  route/build/src/historyFile.f90
  route/build/src/pio_utils.f90
  route/build/src/popMetadat.f90
Labels: cesm-coupling, new features, cleanup, standalone
