Repository ESCOMP/mizuRoute, pull requests merged in 2025-03, with the labels that each got.

#506 Staging for direct insertion implementation
  route/build/Makefile
  route/build/src/data_assimilation.f90
  route/build/src/gageMeta_data.f90
  route/build/src/ncio_utils.f90
  route/build/src/obs_data.f90
  route/build/src/public_var.f90
  route/build/src/read_control.f90
Labels: new features, standalone, science

#521 fix bugs related to fails in restart run with IRF and KWT
  route/build/src/histVars_data.f90
  route/build/src/popMetadat.f90
  route/build/src/var_lookup.f90
Labels: cesm-coupling, bugfix, standalone

#511 Added a new parameter, HYPE_Qsim_mode
  route/build/src/dataTypes.f90
  route/build/src/lake_route.f90
  route/build/src/popMetadat.f90
  route/build/src/process_ntopo.f90
  route/build/src/read_control.f90
  route/build/src/read_streamSeg.f90
  route/build/src/var_lookup.f90
Labels: cesm-coupling, new features, standalone, science

#522 Ensuring Lake Simulation Compatibility with Routing Options Beyond IRF (Cleaning QFUTURE_IRF and UH Allocation)
  route/build/src/init_model_data.f90
  route/build/src/irf_route.f90
  route/build/src/lake_route.f90
  route/build/src/process_ntopo.f90
Labels: cesm-coupling, cleanup, bugfix, standalone

#524 Enhancing `<fname_qsim>` Support: Accepting a single NetCDF file (`file_name.nc`), multiple files via wildcards (`file_name*.nc`), or a text file listing filename(s) (`file_name(s).txt`)
  route/build/src/ncio_utils.f90
  route/build/src/standalone/model_setup.f90
Labels: enhancement, new features, standalone
